# ⚠️ This file is deprecated - Use infra/docker-compose.dev.yml or infra/docker-compose.prod.yml instead
# ⚠️ According to DEV_STANDARD.md, all configs must use env_file instead of hardcoded values

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3017:3017"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - production-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.js
    network_mode: "host"
    env_file:
      - ./backend/.env.production
    restart: unless-stopped
    depends_on:
      - frontend

networks:
  production-network:
    driver: bridge
